apiVersion: v1
kind: Secret
metadata:
  name: twitter-backend-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://adilkhan-m20:Ironman%40123@cluster0.vngczq0.mongodb.net/?appName=Cluster0"
  JWT_SECRET: "SecretKey"
